### ISSUE TITLE
Dependency issue 

### ISSUE THREAD

**Issue by sanjinmehic** [gcremers/metascan-old#1]
Hello, 

I tried to run the metascan command on my sample and got this error: 

 [14:14:12] Looking for 'samtools' - found /usr/local/bin/samtools
[14:14:12] Determined samtools version is 1.14
[14:14:12] Metascan needs samtools 1.6 or higher. Please upgrade and try again.

I installed the latest samtools 1.14 from htslib.org

I am pretty new to coding so I'm not sure if I'm not doing something right, or if your code needs a slight adjustment to treat 1.14 as greater than 1.6. Maybe its thinking its version 1.1? 

Thanks!

**Comment by gcremers** [comment]
Hi Sanjin,

Thank you for your feedback.

After the holidays I will have a look a this. Because of this time restrain and the fact that Metascan is currently under review I am hesitant to make big changes right now.

In the mean time, you could change line 190:  MINVER  => "1.6", to MINVER  => "1.1". 
That should get it going again. Otherwise you could forgo  the --mapping options and do the mapping before using Metascan.


KInd regards,
Geert

**Comment by sanjinmehic** [comment]
No worries, I will try the line 190 change and give it another go. Thank you!
